# Generated by Django 5.0.2 on 2024-03-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ext_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='MRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_table_relationships', to='sample.mtable')),
                ('related_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.mfield')),
                ('related_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_table_relationships', to='sample.mtable')),
            ],
            options={
                'db_table': 'mrelationship',
            },
        ),
    ]
