# Generated by Django 5.0.2 on 2024-03-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_contact_orderdetail_mrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
