# Generated by Django 5.0.2 on 2024-03-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_items'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='items',
            table='items',
        ),
    ]
